import type { Metadata } from "next";
import "./globals.css";
import QueryProviders from "@/lib/providers";
import { Toaster } from "sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <NuqsAdapter>
          <QueryProviders>
            <Toaster />
            {children}
          </QueryProviders>
        </NuqsAdapter>
      </body>
    </html>
  );
}
